### ISSUE TITLE
Submit to CRAN and add example on ipify website 

### ISSUE THREAD

**Issue by daattali** [gregce/ipify#1]
Great little package, it would be nice on CRAN!

I found out about ipify 10 minutes ago. I looked through their API and didn't see R in the long list of languages they support, so I was going to create this package but thankfully you beat me to it. I think it would be nice to include a code sample on thur ipify website, to make it clear that it has an R port!

**Comment by daattali** [comment]
@gregce is there a reason you don't want to submit this to CRAN?

**Comment by daattali** [comment]
If you don't mind, I'd like to fork this and submit to CRAN myself, let me know if you object

**Comment by gregce** [comment]
Hey @daattali Sure, Ill make a note to submit it to CRAN... but to keep me honest, if I don't within a week, 4/5/2020, feel free to fork it and do so :)

**Comment by gregce** [comment]
Submitted this

![image](https://user-images.githubusercontent.com/1565958/78518499-838a9d80-7775-11ea-9ac1-3847cf15d388.png)

**Comment by daattali** [comment]
Right on schedule!

**Comment by asadow** [comment]
This is no longer on CRAN. Should we re-submit?

**Comment by daattali** [comment]
@gregce can you shed some light on why CRAN removed it?
